<?php
/*****************************************************************
*        DO NOT REMOVE                                           *
*        =============                                           *
*PetClinic Management Software                                   *
*Copyrighted 2015-2016 by Michael Avila                          *
*Distributed under the terms of the GNU General Public License   *
*This program is distributed in the hope that it will be useful, *
* but WITHOUT ANY WARRANTY; without even the implied warranty of *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.           *
*****************************************************************/
$expire2min = time() + 60 * 2;
$expire5min = time() + 60 * 5;
$expire1hr = time() + 60 * 60;
$expire10hr = time() + 60 * 60 * 10;
$expire12hr = time() + 60 * 60 * 12;
?>