<?php
/*****************************************************************
*        DO NOT REMOVE                                           *
*        =============                                           *
*PetClinic Management Software                                   *
*Copyrighted 2015-2016 by Michael Avila                          *
*Distributed under the terms of the GNU General Public License   *
*This program is distributed in the hope that it will be useful, *
* but WITHOUT ANY WARRANTY; without even the implied warranty of *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.           *
*****************************************************************/
/*    DO NOT CHANGE THIS INFORMATION!!!!                        */
define('SHA512', "sha512");
define('ENCRYPTION_KEY', 'd0a7e7997b6d5fcd55f4b5c32611b87cd923e88837b63bf2941ef819dc8ca282');
define('p_key', '9adf09239f60ab39ecd1e46e5886ef718cddddef1547cc07dccf27efd79eae6f');
define('ps_key','9adf09238f60ab39ecd1e46e5886ef718cddddef1547cd07dccf27efd79eae6f');
define('ss_key','5def753ac06defcd02395abcdef0987654321def1547cd07dccf27efd79eae6f');
define('sx_key','9adf09239f60ab39ecd1e46e5886ef718cddddef1547cc07dccfd7efd19eae6f');
define('zero',  '0acbe5903fac532efaefb3690fdd6f718cddddef1547cc07dccfe7efd29eae60');
define('one',   '1abe693b4c60aeaae500e21ebc86ee23789dabcdef49310feccf04ead39eae61');
define('two',   '2345678901abcdef0987654321fedcba8ffd4d1f1047df07d14ff7efd497ad62');
define('three', '3adc0473df308bf95cd1e46e5e86ef708caad3e41547dc07d23f4cea58febe23');
?>