<?php
/*****************************************************************
*        DO NOT REMOVE                                           *
*        =============                                           *
*VetClinic Management Software                                   *
*Copyrighted 2015-2016 by Michael Avila                          *
*Distributed under the terms of the GNU General Public License   *
*This program is distributed in the hope that it will be useful, *
* but WITHOUT ANY WARRANTY; without even the implied warranty of *
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.           *
*****************************************************************/
$user = "pcmsuser";
$password = 'rsCgZ/SuHpJhtV2K6/8hwMBTqaBPf5rZR5D0Di//C8703HTRBbEIYvmneKgU952D5tiHYh72/rP3jz3MIuZPCrPVWYT70pP+QGq0+rSySURWTlQSScS/hhKN+rRBXmGU|DI27bsSPpwmmtE5uPt8+Wj+ESmJJC83JKqqlgfvsXuU=';
$suser = 'JxLU1/LvtbMYZr7JqwqnWe3v9A59k/qszCnlMYQGMrh/7ssHhbfx0ySGnizrU90sbn7tIJKU4nBhqAItecQXmA9xUmkekNiKnShRlE0dAu2eHawNgX9BNIh9aHXrBJrP|Qf+WV22lMsDt2A/AIg7GgmlqkpmPmOlVlAwT4xuyFFM=';
$spassword = 'FRcUA4tYk54bDcgyWgZdd+r6Em18Ntx7tvmwGRv05qkIV3z4BrLze+qTp5c5WE19gbW2dDzdbFATEWO1P1R5uxqNuMgSG3+9QDPY4kbuXyLSMII3/5f7T43k5RwZ+D3u|K7SGUCQs0N5FfSs5U89wOOkvFjuTu6A9YgNGFgNXdPA=';
?>